config/routes.rb
Rails.application.routes.draw do
  root  "characters#index"
  
  get '/characters', to: 'characters#index', as: 'characters'

  get '/characters/new', to: 'characters#new', as: 'new_character'
  post '/characters', to: 'characters#create'

  get '/characters/:id', to: 'characters#show', as: 'character'

  get '/characters/:id/edit', to: 'characters#edit', as: 'edit_character'
  patch '/characters/:id', to: 'characters#update'

  delete '/characters/:id', to: 'characters#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
    before_action :set_character, only: [:show, :edit, :update, :destroy]

    def index
        @characters = Character.all
    end

    def new
        @character = Character.new
    end

    def create
        @character = Character.new(character_params)

        if @character.save
            flash[:notice] = "message"
            # redirect_to @character, notice: 'Character was successfully created'
            redirect_to characters_path
        else
            render :new
        end

    end

    def show
    end

    def edit
    end

    def update
        if @character.update(character_params)
            redirect_to @character
        else
            render :edit
        end
    end

    def destroy
        if @character.destroy
            redirect_to characters_path
        end
    end

    private
        def set_character
            @character = Character.find(params[:id])
        end

        def character_params
            params.require(:character).permit(:name, :race, :role, :strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_with model: @character do |form| %>
    <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
        <% character.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  
    <div class="field">
      <%= form.label :race %>
      <%= form.select :race, ["Human", "Dwarf", "Elf"] %>
    </div>

    <div class="field">
    <%= form.label :role %>
    <%= form.select :role, ["Barbarian", "Fighter", "Druid", "Wizard", "Sorcerer", "Warlock", "Ranger", "Paladin", "Monk" ] %>
    </div>

    <div class="field">
    <%= form.label :strength %>
    <%= form.number_field :strength, in: 1..20, step: 1 %>
    </div>

    <div class="field">
    <%= form.label :dexterity %>
    <%= form.number_field :dexterity, in: 1..20, step: 1 %>
    </div>

    <div class="field">
    <%= form.label :constitution %>
    <%= form.number_field :constitution, in: 1..20, step: 1 %>
    </div>

    <div class="field">
    <%= form.label :intelligence %>
    <%= form.number_field :intelligence, in: 1..20, step: 1 %>
    </div>

    <div class="field">
    <%= form.label :wisdom %>
    <%= form.number_field :wisdom, in: 1..20, step: 1 %>
    </div>

    <div class="field">
    <%= form.label :charisma %>
    <%= form.number_field :charisma, in: 1..20, step: 1 %>
    </div>

    
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

app/views/characters/edit.html.erb
<h1> Edit Character </h1>

<%= render 'form', character: @character %>


<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
# <p id="notice"><%= notice %></p>
<h1>Characters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Race</th>
      <th>Role</th>
      <th>STR</th>
      <th>DEX</th>
      <th>CON</th>
      <th>INT</th>
      <th>WIS</th>
      <th>CHA</th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.name %></td>
        <td><%= character.race %></td>
        <td><%= character.role %></td>

        <td><%= character.strength %></td>
        <td><%= character.dexterity %></td>
        <td><%= character.constitution %></td>
        <td><%= character.intelligence %></td>
        <td><%= character.wisdom %></td>
        <td><%= character.charisma %></td>

        <td><%= link_to 'Show', character %></td>
        <td><%= link_to 'Edit', edit_character_path(character) %></td>
        <td><%= link_to 'Destroy', character_path(character), method: :delete, data: { confirm: 'Are you sure you want to delete this character?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<td><%= link_to 'Add', new_character_path %></td>

app/views/characters/new.html.erb
<h1> New Character </h1>


<%= render 'form', character: @character %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Race:</strong>
  <%= @character.race %>
</p>

<p>
  <strong>Role:</strong>
  <%= @character.role %>
</p>


<p>
  <strong>STR:</strong>
  <%= @character.strength %>
</p>

<p>
  <strong>DEX:</strong>
  <%= @character.dexterity %>
</p>

<p>
  <strong>CON:</strong>
  <%= @character.constitution %>
</p>

<p>
  <strong>INT:</strong>
  <%= @character.intelligence %>
</p>


<p>
  <strong>WIS:</strong>
  <%= @character.wisdom %>
</p>

<p>
  <strong>CHA:</strong>
  <%= @character.charisma %>
</p>



<%= link_to 'Back', characters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dndcreate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>